MVC/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Interfaces;
using MVC.Models;
using MVC.ViewModels;

namespace MVC.Controllers;

public class ShopCartController : Controller
{
    private IAllCars _carRep;
    private readonly ShopCart _shopCart;

    public ShopCartController(IAllCars carRep, ShopCart shopCart)
    {
        _carRep = carRep;
        _shopCart = shopCart;
    }

    public ViewResult Index()
    {
        var items = _shopCart.GetShopItems();
        _shopCart.ListShopItems = items;

        var obj = new ShopCartViewModel
        {
            shopCart = _shopCart
        };

        return View(obj);
    }

    public RedirectToActionResult addToCart(int id)
    {
        var item = _carRep.Cars.FirstOrDefault(i => i.Id == id);
        if (item != null)
        {
            _shopCart.AddToCart(item);
        }
        return RedirectToAction("Index");
    }

    public RedirectToActionResult RemoveFromCart(int id)
    {
        var item = _carRep.Cars.FirstOrDefault(i => i.Id == id);
        if (item != null)
        {
            _shopCart.RemoveFromCart(item);
        }
        return RedirectToAction("Index");
    }
}

MVC/Views/Shared/AllCars.cshtml
@model MVC.Models.Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.Image" alt="@Model.Name" />
    <h2>@Model.Name</h2>
    <p>@Model.Description</p>
    <p>Ціна: @Model.Price.ToString() $</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.Id">Додати в корзину</a></p>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header data-bs-theme="dark">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">MVC-MARKET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List">Автомобілі</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/electro">Електро</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/fuel">Бензинові</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/Add">Додати авто</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/Delete">Видалити авто</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container fixed-bottom bg-white">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2024 Всі права захищені · <a href="#">Згода</a> · </p>
    </footer>
</body>
</html>